services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    goyden_image_crop:
      class: App\Goyden\ImageCropBundle\GoydenImageCropBundle
      arguments:
        $thumbnails: []